[package]
name = "wvl"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3" }
uom = "0.36.0"
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "24.0"

[[bin]]
name = "wvl"
path = "main.rs"
